const IMAGES = {
  case1J1: require('./cases1.jpg').default,
  case1J2: require('./cases1@2x.jpg').default,
  case1W1: require('./cases1.webp').default,
  case1W2: require('./cases1@2x.webp').default,
  case2J1: require('./cases3.jpg').default,
  case2J2: require('./cases3@2x.jpg').default,
  case2W1: require('./cases3.webp').default,
  case2W2: require('./cases3@2x.webp').default,
  case3J1: require('./cases5.jpg').default,
  case3J2: require('./cases5@2x.jpg').default,
  case3W1: require('./cases5.webp').default,
  case3W2: require('./cases5@2x.webp').default,
  case4J1: require('./cases7.jpg').default,
  case4J2: require('./cases7@2x.jpg').default,
  case4W1: require('./cases7.webp').default,
  case4W2: require('./cases7@2x.webp').default,
  case5J1: require('./cases2.jpg').default,
  case5J2: require('./cases2@2x.jpg').default,
  case5W1: require('./cases2.webp').default,
  case5W2: require('./cases2@2x.webp').default,
  case6J1: require('./cases4.jpg').default,
  case6J2: require('./cases4@2x.jpg').default,
  case6W1: require('./cases4.webp').default,
  case6W2: require('./cases4@2x.webp').default,
};

export default IMAGES;
